oauth_client/urls.py
from django.urls import path

from oauth_client.views import OAuth2CallbackView, ProviderCreateView, \
    ProviderUpdateView, ProviderDeleteView, ProviderListView

app_name = 'oauth_client'
urlpatterns = [
    path('oauth2_callback/<int:provider_id>/',
         OAuth2CallbackView.as_view(),
         name='oauth2_callback'),
    path('oauth2_callback/<path:provider_slug>/',
         OAuth2CallbackView.as_view(),
         name='oauth2_callback'),
    path('oauth2_callback/<path:provider_slug>/',
         OAuth2CallbackView.as_view(),
         name='oauth2_callback_part'),

    path('provider/add/',
         ProviderCreateView.as_view(),
         name='provider-create'),
    path('provider/<int:pk>/change/',
         ProviderUpdateView.as_view(),
         name='provider-update'),
    path('provider/<int:pk>/delete/',
         ProviderDeleteView.as_view(),
         name='provider-delete'),
    path('provider/list/',
         ProviderListView.as_view(),
         name='provider-list'),
]

oauth_client/templates/oauth_client/provider_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>{% block title %}OAuth Client{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'oauth_client:provider-list' %}">OAuth Client</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsDefault"
                aria-controls="navbarsDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsDefault">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'oauth_client:provider-list' %}">Все провайдеры</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<main class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}
</main>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

oauth_client/templates/oauth_client/provider_confirm_delete.html
{% extends "oauth_client/provider_base.html" %}

{% block content %}

    <h1 class="h2 mt-3 mb-3">
        Удаление провайдера "{{ object }}"
    </h1>

    <form method="post">
        {% csrf_token %}
        <p>Вы точно хотите удалить "{{ object }}"?</p>
        <button class="btn btn-danger" type="submit">Удалить</button>
    </form>

{% endblock %}

oauth_client/templates/oauth_client/provider_form.html
{% extends "oauth_client/provider_base.html" %}

{% block content %}

    <h1 class="h2 mt-3 mb-3">
        {% if object %}
            Провайдер "{{ object.name }}"
        {% else %}
            Добавить провайдера
        {% endif %}
    </h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Сохранить</button>
    </form>

{% endblock %}

oauth_client/templates/oauth_client/provider_list.html
{% extends "oauth_client/provider_base.html" %}

{% block content %}

    <h1 class="h2 mt-3 mb-3">Провайдеры</h1>
    <p>
        <a class="btn btn-primary" href="{% url 'oauth_client:provider-create' %}">+ Добавить</a>
    </p>
    <ul>
        {% for provider in object_list %}
            <li>
                <a href="{% url 'oauth_client:provider-update' pk=provider.pk %}">{{ provider.name }}</a>
                <a href="{% url 'oauth_client:provider-delete' pk=provider.pk %}" class="text-danger">&times;</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}